# @package _global_
env: gym.Humanoid-v3

max_episode_steps: 1000
max_test_episode_steps: 1500

# num_train_steps: 4e6
# num_steps_per_skill: 1e6
# replay_buffer_capacity: 2e6

# num_seed_steps: 5000
# eval_frequency: 50

collected_trajectories: 5e2
alpha: 60.0
beta: 1.0

# Test config

# num_train_steps: 1000
# num_steps_per_skill:
#   - 100
#   - 200
#   - 300
#   - 400
# replay_buffer_capacity: 1000

# num_seed_steps: 5
# eval_frequency: 5

# Variable length

num_train_steps: 3e7
num_steps_per_skill: 
  - 5e6
  - 5e6
  - 5e6
  - 5e6
  - 5e6
  - 5e6
  # - 5e4
  # - 5e4
  # - 5e4
  # - 25e4
  # - 25e4
replay_buffer_capacity: 1e7

num_seed_steps: 10000
eval_frequency: 50
