# @package _global_
env: dm.swimmer_6

max_episode_steps: 100
max_test_episode_steps: 500

num_train_steps: 25e5
num_steps_per_skill: 25e4
replay_buffer_capacity: 5e5

num_seed_steps: 5000
eval_frequency: 25

collected_trajectories: 1e2
alpha: 2500.0
beta: 1.0